name: lint_format_test.yml
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - closed

jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:

      # Checkout repo
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.head_ref }}

      - name: Setup Python
        uses: actions/setup-python@v6.2.0
        with:
          python-version-file: .python-version

      # Setup uv. uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39
      - name: astral-sh/setup-uv
        uses: astral-sh/setup-uv@v8.2.0

  lint-format-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: setup
    steps:
      - id: ruff-lint
        run: |
          uv run ruff check .

      - id: ruff-format
        run: |
          uv run ruff format .

      - id: pytest-test
        run: |
          uv run --group test pytest
